import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Parallax, Background  } from 'react-parallax'
import Earth from "../public/bg.jpg"
import Frontpage from '../components/Frontpage'
import Navbar from '../components/Navbar'
import Desc from '../components/Desc'
import Gallery from '../components/Gallery'
import Ideas from '../components/Ideas'
import Packages from '../components/Packages'
import Reviews from '../components/Reviews'
import Contact from '../components/Contact'
import Upcoming from '../components/Upcoming'
import Footer from '../components/Footer'


export default function Home() {


  return (
    <div>
      <Head>
        <title>Travel | Agency </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Frontpage />
      <Gallery />
      <Upcoming />
      <Desc />
      <Ideas />
      <Packages />
       <Contact />
       <Footer />
      </div>
  )
}
